name: model
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.*
  - pip
  - matplotlib
  - numpy
  - matplotlib
  - pytorch==1.11.0
  - torchvision
  - captum=0.5.0=0
  - scikit-learn
  - scipy